# Generated by Django 4.2.7 on 2023-11-18 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oracleDB", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="choice",
            table="Choice",
        ),
        migrations.AlterModelTable(
            name="question",
            table="Question",
        ),
    ]
