# Generated by Django 4.2.7 on 2023-11-18 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oracleDB", "0002_alter_choice_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="choice",
            table="ORACLEDB_CHOICE",
        ),
        migrations.AlterModelTable(
            name="question",
            table="ORACLEDB_QUESTION",
        ),
    ]
