# Generated by Django 4.2.7 on 2023-12-01 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_choice_table_alter_question_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
    ]
